kind: DaemonSet
replicaCount: 1

image:
  repository: cr.fluentbit.io/fluent/fluent-bit
  tag: latest
  # tag: latest-debug # USe this if you need a shell in the container to debug.

config:
  outputs: |
    [OUTPUT]
        Name        stackdriver
        Match       kube.*
        Resource    k8s_container
        k8s_cluster_name NAMEOFTHECLUSTER
        k8s_cluster_location  LOCATIONOFTHECLUSTER
        tag_prefix  on_prem_k8s.
        google_service_credentials /var/run/google-service-credentials/key.json
        Retry_Limit 5
        workers 1

    [OUTPUT]
        Name        stackdriver
        Match       host.*
        Resource    k8s_node
        k8s_cluster_name NAMEOFTHECLUSTER
        k8s_cluster_location  LOCATIONOFTHECLUSTER
        tag_prefix  on_prem_k8s.
        google_service_credentials /var/run/google-service-credentials/key.json
        Retry_Limit 5
        workers 1

daemonSetVolumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers
  - name: etcmachineid
    hostPath:
      path: /etc/machine-id
      type: File
  - name: google-service-credentials
    secret:
      secretName: google-service-credentials
      optional: false

daemonSetVolumeMounts:
  - name: varlog
    mountPath: /var/log
  - name: varlibdockercontainers
    mountPath: /var/lib/docker/containers
    readOnly: true
  - name: etcmachineid
    mountPath: /etc/machine-id
    readOnly: true
  - name: google-service-credentials
    mountPath: "/var/run/google-service-credentials"
    readOnly: true

logLevel: info # set to debug to... debug
